services:
  discusshub:
    container_name: discusshub
    image: mysql:latest
    environment:
      MYSQL_DATABASE: discusshub-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - discusshub:/var/lib/mysql
    networks:
      - discusshub-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "discusshub", "--password=password" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  discusshub-api:
    container_name: discusshub-platform
    image: gitpatrickv/discusshub-platform:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - discusshub-network
    depends_on:
      discusshub:
        condition: service_healthy

volumes:
  discusshub:

networks:
  discusshub-network:
    driver: bridge
